USE [master]
GO

/****** Object:  Database [db_Auction]    Script Date: 7/2/2022 2:08:38 PM ******/
CREATE DATABASE [db_Auction]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_Auction', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\db_Auction.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_Auction_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\db_Auction_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_Auction].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_Auction] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_Auction] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_Auction] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_Auction] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_Auction] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_Auction] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_Auction] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_Auction] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_Auction] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_Auction] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_Auction] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_Auction] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_Auction] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_Auction] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_Auction] SET  ENABLE_BROKER 
GO

ALTER DATABASE [db_Auction] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_Auction] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_Auction] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_Auction] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_Auction] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_Auction] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_Auction] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_Auction] SET RECOVERY FULL 
GO

ALTER DATABASE [db_Auction] SET  MULTI_USER 
GO

ALTER DATABASE [db_Auction] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_Auction] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_Auction] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_Auction] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_Auction] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_Auction] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [db_Auction] SET QUERY_STORE = OFF
GO

ALTER DATABASE [db_Auction] SET  READ_WRITE 
GO


